/* eslint-disable */

import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Card, Paper, Progress, Text, Stack, Grid } from "@mantine/core";

import { api } from "../utils/api";
import { useRouter } from "next/router";
import Amb from "../components/Amb";

const Home: NextPage = () => {
  const router = useRouter();
  const { campaignId, source } = router.query;

  const { data, isLoading, isError } = api.amb.amb.useQuery(
    {
      campaignId: typeof campaignId == "string" ? campaignId : undefined,
      source:
        typeof source == "string" &&
        (source == "excel" || source == "powerlink")
          ? source
          : undefined,
    },
    { refetchInterval: 30000 }
  );

  if (isLoading) return <p>loading...</p>;
  if (isError) return <p>error loading data</p>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-4" dir="rtl">
        <div className="-mx-1 mt-1 flex flex-wrap ">
          {data.map(({ name, amountILS, amountUSD, percent, target }, i) => (
            <Amb
              name={name}
              amountILS={amountILS}
              percent={percent}
              target={target}
              key={i}
            />
          ))}
        </div>
      </div>
    </>
  );
};

export default Home;
