/* eslint-disable */

import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Card, Paper, Progress, Text, Stack, Grid } from "@mantine/core";

import { api } from "../utils/api";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();

  const campaignId =
    typeof router.query.id === "string"
      ? router.query.id
      : "177b5cd5-2a69-4933-992e-1dd3599eb77e";

  const { data, isLoading, isError } = api.amb.data.useQuery(
    {
      id: campaignId,
    },
    { refetchInterval: 30000 }
  );

  if (isLoading) return <p>loading...</p>;
  if (isError) return <p>error loading data</p>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-4" dir="rtl">
        {/* <Card withBorder radius="md" p="xl" shadow="md">
          <Text size="lg" weight={500}>
            {`${data.target}₪ / ${data.totalAmountILS}₪`}
          </Text>
          <Progress value={data.percent} mt="md" size="lg" radius="xl" />
        </Card> */}

        <div className="-mx-1 mt-1 flex flex-wrap ">
          {data.map(({ name, amountILS, amountUSD, percent }, i) => (
            <Paper
              key={i}
              p={4}
              className="w-full sm:w-1/2 md:w-1/3 lg:w-1/4 xl:w-1/5"
            >
              <Card withBorder h={150} shadow="md" radius="md">
                <Text color="blue" weight="bolder" fz={18} align="center">
                  {name}
                </Text>
                <Text color="green" fz={20} align="center">
                  {amountILS.toFixed(0)}₪
                </Text>

                <Progress value={percent} mt="md" size="lg" radius="xl" />
              </Card>
            </Paper>
          ))}
        </div>
      </div>
    </>
  );
};

export default Home;
