/* eslint-disable */

import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Card, Paper, Progress, Text, Stack, Grid } from "@mantine/core";

import { api } from "../utils/api";
import { useRouter } from "next/router";
import Donation from "../components/Donation";

const Home: NextPage = () => {
  const router = useRouter();
  const { campaignId, source, ambId } = router.query;

  const { data, isLoading, isError } = api.donations.donations.useQuery(
    {
      campaignId: typeof campaignId == "string" ? campaignId : undefined,
      source:
        typeof source == "string" &&
        (source == "excel" || source == "powerlink")
          ? source
          : undefined,
      ambId: typeof ambId == "string" ? ambId : undefined,
    },
    { refetchInterval: 30000 }
  );

  if (isLoading) return <p>loading...</p>;
  if (isError) return <p>error loading data</p>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-4" dir="rtl">
        <Card withBorder radius="md" p="xl" shadow="md">
          <Text size="lg" weight={500}>
            {`${data.target.toFixed(0)}₪ / ${data.totalAmountILS.toFixed(0)}₪`}
          </Text>
          <Progress value={data.percent} mt="md" size="lg" radius="xl" />
        </Card>

        <div className="-mx-1 mt-1 flex flex-wrap ">
          {data.donations.map(
            ({ dedication, name, amountILS, amountUSD, amb, currency }, i) => (
              <Donation
                amb={amb}
                dedication={dedication}
                amountILS={amountILS}
                name={name}
                key={i}
              />
            )
          )}
        </div>
      </div>
    </>
  );
};

export default Home;
