/* eslint-disable */

import {
  Card,
  Paper,
  Progress,
  Text,
  Stack,
  Grid,
  Container,
} from "@mantine/core";
import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Stack align={"center"}>
          <Link href={"/amb?source=powerlink"}>שגרירים powerlink</Link>
          <Link href={"/amb?source=excel"}>שגרירים excel</Link>
          <Link href={"/donations?source=powerlink"}>תרומות powerlink</Link>
          <Link href={"/donations?source=excel"}>תרומות excel</Link>
        </Stack>
      </Container>
    </>
  );
};

export default Home;
