import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const { data, isLoading, isError } = api.donations.data.useQuery({
    id: "from tRPC",
  });

  if (isLoading) return <p>loading...</p>;
  if (isError) return <p>error loading data</p>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-4">
        <h2 className="mb-4 text-2xl font-bold">Donation List</h2>
        <div className="-mx-2 flex flex-wrap">
          {data.donations.map(({ amount, dedication, name }, i) => (
            <div
              className="w-full p-2 sm:w-1/2 md:w-1/3 lg:w-1/4 xl:w-1/5"
              key={i}
            >
              <div className="h-48 text-clip rounded-lg bg-white p-6 shadow-lg">
                <div className="mb-2 text-3xl font-bold text-indigo-500">
                  {name}
                </div>
                <div className="mb-4 text-xl font-medium text-teal-500">
                  ₪{amount}
                </div>
                <div className="text-sm text-gray-700">{dedication}</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default Home;
